Areas/Admin/Controllers/InjectionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlinePharmacyStore.DataAccess.Repository.IRepository;
using OnlinePharmacyStore.Models;
using OnlinePharmacyStore.Models.CommonPropertyDirectory;

namespace OnlinePharmacyStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class InjectionsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment webHostEnvironment;

        public InjectionsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            this.webHostEnvironment = webHostEnvironment;
        }

        // GET: Admin/Injections
        public IActionResult Index()
        {
            return _unitOfWork.Injection != null ?
                        View(_unitOfWork.Injection.GetAll()) :
                        Problem("Entity set 'AppDbContext.Injections'  is null.");
        }

        // GET: Admin/Injections/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _unitOfWork.Injection == null)
            {
                return NotFound();
            }

            var injection = _unitOfWork.Injection
                .GetFirstOrDefault(m => m.Id == id);
            if (injection == null)
            {
                return NotFound();
            }

            return View(injection);
        }

        // GET: Admin/Injections/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: Admin/Injections/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to.
        //For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,GenericName,BrandName,Country,Price,MRPRs,MfgDate,ExpDate,ImageUrl,BatchNo,centigrade,Milliliter")] Injection injection, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    _unitOfWork.Injection.SaveImage(injection, file, webHostEnvironment.WebRootPath);
                }
                _unitOfWork.Injection.Add(injection);
                _unitOfWork.Save();
                TempData["success"] = "Created Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(injection);
        }

        // GET: Admin/Injections/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || _unitOfWork.Injection == null)
            {
                return NotFound();
            }



            var injection = _unitOfWork.Injection.GetFirstOrDefault(u => u.Id == id);
            if (injection == null)
            {
                return NotFound();
            }
            return View(injection);
        }

        //// POST: Admin/Injections/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,GenericName,BrandName,Country,Price,MRPRs,MfgDate,ExpDate,ImageUrl,BatchNo,centigrade,Milliliter")] Injection injection, IFormFile file)
        {
            if (id != injection.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                _unitOfWork.Injection.Update(injection, file, webHostEnvironment.WebRootPath);
                _unitOfWork.Save();
                TempData["success"] = "Updated Succeffuly!";
                return RedirectToAction(nameof(Index));
            }
            return View(injection);
        }

        //// GET: Admin/Injections/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Injections == null)
        //    {
        //        return NotFound();
        //    }

        //    var injection = await _context.Injections
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (injection == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(injection);
        //}

        //// POST: Admin/Injections/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Injections == null)
        //    {
        //        return Problem("Entity set 'AppDbContext.Injections'  is null.");
        //    }
        //    var injection = await _context.Injections.FindAsync(id);
        //    if (injection != null)
        //    {
        //        _context.Injections.Remove(injection);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool InjectionExists(int id)
        //{
        //  return (_context.Injections?.Any(e => e.Id == id)).GetValueOrDefault();
        //}
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlinePharmacyStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlinePharmacyStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">OnlinePharmacyStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Injections" asp-action="index">Injection</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlinePharmacyStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>